import {empire,travel,userVenture} from './business-world.js';
import {socialWorld,createFriend,simulateLife} from './social-world.js';
import {SCENES} from './scenes.js';
const $=s=>document.querySelector(s),content=$('#content'),msgs=$('#messages');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const get=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let current='today',voice=get('neo3.voice',true),cache=get('neo3.feed',{items:[],errors:[],at:0}),weather=get('neo3.weather',null),saved=get('neo3.saved',[]),history=get('neo3.chat',[]),requestSeq=0,busy=false;
const pending=new Map();
window.neoFetchResult=(id,data,error)=>{const p=pending.get(id);if(p){clearTimeout(p.timer);pending.delete(id);error?p.reject(Error(error)):p.resolve(data)}};
function net(url){if(window.AndroidNeo)return new Promise((resolve,reject)=>{let id=String(++requestSeq);let timer=setTimeout(()=>{pending.delete(id);reject(Error('Délai dépassé'))},30000);pending.set(id,{resolve,reject,timer});AndroidNeo.fetch(id,url)});return fetch(url,{signal:AbortSignal.timeout(20000)}).then(r=>{if(!r.ok)throw Error('Source indisponible');return r.text()})}
window.neoSpeaking=on=>$('#neo').classList.toggle('talking',on);
function say(text,force=false){if(!voice&&!force)return;if(window.AndroidNeo){AndroidNeo.speak(text);return}if(!window.speechSynthesis){$('#status').textContent='Lecture vocale indisponible ici.';return}speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.lang='fr-FR';u.rate=.94;u.onstart=()=>window.neoSpeaking(true);u.onend=u.onerror=()=>window.neoSpeaking(false);speechSynthesis.speak(u)}
function stop(){if(window.AndroidNeo)AndroidNeo.stop();else window.speechSynthesis?.cancel();window.neoSpeaking(false)}
window.neoVoiceStatus=t=>$('#status').textContent=t;window.neoVoiceError=window.neoVoiceStatus;
window.neoTranscript=q=>{$('#q').value=q;$('#chat').requestSubmit()};
$('#listen').onclick=()=>{stop();if(window.AndroidNeo){AndroidNeo.listen();return}let R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){window.neoVoiceError('Micro indisponible ici. Tu peux écrire.');return}let r=new R();r.lang='fr-FR';r.onresult=e=>window.neoTranscript(e.results[0][0].transcript);r.onerror=()=>window.neoVoiceError('Micro indisponible : réessaie.');r.start()};
$('#voice').onclick=()=>{voice=!voice;put('neo3.voice',voice);$('#voice').textContent=voice?'🔊':'🔇';if(!voice)stop()};$('#voice').textContent=voice?'🔊':'🔇';
const when=t=>new Date(t).toLocaleString('fr-FR',{timeZone:'Africa/Dar_es_Salaam',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});
function parseFeed(xml,category){const d=new DOMParser().parseFromString(xml,'application/xml');if(d.querySelector('parsererror'))throw Error('Flux illisible');const plain=s=>{let h=new DOMParser().parseFromString(s,'text/html');return h.body.textContent.trim()};return [...d.querySelectorAll('item,entry')].slice(0,15).map(e=>({category,title:plain(e.querySelector('title')?.textContent||''),text:plain(e.querySelector('description,summary')?.textContent||'').slice(0,1500),url:e.querySelector('link')?.getAttribute('href')||e.querySelector('link')?.textContent||'',at:Date.parse(e.querySelector('pubDate,updated,published')?.textContent||''),source:e.querySelector('source')?.textContent||(category==='MONDE'?'BBC':category==='TSUNAMI'?'NOAA NTWC':'Presse via Google Actualités')})).filter(x=>x.title&&Number.isFinite(x.at)&&x.url.startsWith('https://'))}
async function refresh(){if(busy)return;busy=true;$('#ticker').textContent='Actualisation des sources…';
const sources=[['MONDE','https://feeds.bbci.co.uk/news/world/rss.xml'],['TANZANIE','https://news.google.com/rss/search?q=Zanzibar%20Tanzania%20when%3A2d&hl=fr&gl=FR&ceid=FR%3Afr'],['HUMANOÏDES','https://news.google.com/rss/search?q=robots%20humanoides%20when%3A2d&hl=fr&gl=FR&ceid=FR%3Afr'],['TSUNAMI','https://www.tsunami.gov/events/xml/PAAQAtom.xml']];
let results=await Promise.allSettled(sources.map(async([cat,url])=>({cat,items:parseFeed(await net(url),cat)})));let next=[],errors=[];results.forEach((r,i)=>{let cat=sources[i][0];if(r.status==='fulfilled')next.push(...r.value.items);else{errors.push(cat);next.push(...cache.items.filter(x=>x.category===cat))}});cache={items:next,errors,at:Date.now()};put('neo3.feed',cache);
try{let j=JSON.parse(await net('https://api.open-meteo.com/v1/forecast?latitude=-6.4167&longitude=39.55&hourly=temperature_2m,precipitation_probability,precipitation,wind_speed_10m&forecast_days=2&timezone=Africa%2FDar_es_Salaam'));if(!j.hourly?.time)throw Error('Prévisions indisponibles');weather={...j,checked:Date.now()};put('neo3.weather',weather)}catch{errors.push('MÉTÉO');put('neo3.feed',cache)}busy=false;render();$('#ticker').textContent=errors.length?'Sources indisponibles : '+errors.join(', '):'Sources actualisées · '+when(cache.at)}
function freshItems(){return cache.items.filter(x=>Date.now()-x.at<72*3600000&&x.at<=Date.now()+300000).sort((a,b)=>b.at-a.at)}
function cards(items){return items.map((n,i)=>`<article class="card"><span class="tag">${esc(n.category)} · ${when(n.at)}</span><h2>${esc(n.title)}</h2><p>${esc(n.text||'Consulte la source pour lire l’article complet.')}</p><footer>${esc(n.source)}</footer><div class="cardActions"><a href="${esc(n.url)}" target="_blank" rel="noopener">Lire la source ↗</a><button data-read="${i}">▶ Écouter</button><button data-save="${i}">♡ Garder</button></div></article>`).join('')||'<p>Aucun bulletin récent disponible. Appuie sur Actualiser avec Internet. Une source inaccessible ne signifie pas qu’il n’existe aucune alerte.</p>'}
let shown=[];
function alerts(){let h=weather?.hourly,now=Date.now(),rows=[];if(h)rows=h.time.map((t,i)=>({t,ms:Date.parse(t+'+03:00'),p:h.precipitation_probability[i],mm:h.precipitation[i],temp:h.temperature_2m[i],wind:h.wind_speed_10m[i]})).filter(x=>x.ms>=now-3600000).slice(0,12);shown=freshItems().filter(x=>x.category==='TSUNAMI');return `<article class="card"><span class="tag">MAKUNDUCHI · PRÉVISIONS</span><h2>Pluie heure par heure</h2><p>Prévisions Open-Meteo, distinctes des alertes officielles TMA.${weather?' Vérification : '+when(weather.checked)+'.':''}</p>${weather&&Date.now()-weather.checked>6*3600000?'<p class="warning">Données anciennes : actualise avant de les utiliser.</p>':''}<div class="tableWrap"><table><tr><th>Heure</th><th>Pluie</th><th>mm</th><th>°C</th><th>Vent km/h</th></tr>${rows.map(x=>`<tr><td>${when(x.ms)}</td><td>${x.p??'—'} %</td><td>${x.mm??'—'}</td><td>${x.temp??'—'}</td><td>${x.wind??'—'}</td></tr>`).join('')}</table></div><p>${rows.length?'Probabilité de pluie : consulte l’heure et la quantité prévues.':'Prévisions non téléchargées.'}</p><a href="https://www.meteo.go.tz/">Consulter la TMA ↗</a></article><article class="card"><h2>Bulletins tsunami</h2><p>Flux NOAA NTWC, dont la couverture ne garantit pas le suivi de Zanzibar. Ces bulletins peuvent annoncer l’absence de menace ; lis leur contenu. L’application ne surveille pas les alertes lorsqu’elle est fermée.</p><a href="https://www.tsunami.gov/">Centres d’alerte officiels ↗</a></article>${cards(shown)}`}
function business(){let e=empire();return `<article class="card"><span class="tag">VOYAGES & ENTREPRISES · MONDE SIMULÉ</span><h2>Néo à ${esc(e.location)}</h2><p>Les voyages et sociétés de Néo sont fictifs. Les idées deviennent des plans de travail à valider avec de vrais clients.</p><div class="cardActions"><button id="travel">🌍 Prochaine destination</button><button id="venture">Construire mon entreprise</button><button id="readBusiness">▶ Raconte-moi</button></div></article><div class="metrics"><div><strong>${e.trips.length}</strong><small>escales</small></div><div><strong>${e.ideas.length}</strong><small>pistes étudiées</small></div><div><strong>${e.companies.length}</strong><small>sociétés fictives</small></div></div>${e.ideas.slice(0,10).map(i=>`<article class="card"><span class="tag">${esc(i.market)}</span><h3>${esc(i.title)}</h3><p>${esc(i.why)}</p></article>`).join('')}<h3>Entreprises de Néo</h3>${e.companies.map(c=>`<article class="card"><h3>${esc(c.name)}</h3><p>${esc(c.sector)} · revenus réels : 0 €</p></article>`).join('')}<h3>Carnet de voyage</h3>${e.activity.slice(0,15).map(x=>`<p>${when(x.at)} · ${esc(x.text)}</p>`).join('')}`}
function businessStory(){let e=empire(),i=e.ideas[0];return `Amelle, mon carnet de voyage simulé m’amène à ${e.location}. ${i?'J’y explore '+i.title+'. Mon hypothèse est la suivante : '+i.why+'.':''} Avant de créer une entreprise, je commencerais par dix conversations avec des clients potentiels. Je leur demanderais ce qu’ils font aujourd’hui, le temps qu’ils perdent et ce qu’ils ont déjà essayé. Puis je préparerais une offre très simple, avec un résultat précis et un prix à tester. L’objectif de cette première semaine serait d’obtenir une demande payante, pas seulement des compliments. Pour Prestigia, le travail concret consiste à vérifier qu’un particulier peut déposer une demande, qu’un artisan peut s’inscrire et qu’un courriel arrive vraiment. Ensuite, on mesure les demandes reçues, les demandes qualifiées et les ventes. Aucun revenu n’est garanti par cette simulation. Nous pouvons utiliser ce carnet pour choisir une action à réaliser aujourd’hui.`}
function plan(){let p=userVenture('Prestigia — plan d’Amelle');let text=`${p.name}\nPiste explorée : ${p.concept}\nMarché à étudier : ${p.target}\n\n1. Choisir un seul service et une seule ville.\n2. Interroger dix clients sur leurs besoins.\n3. Définir une offre et un prix test.\n4. Vérifier le formulaire et les courriels de bout en bout.\n5. Obtenir une première commande payante.\n6. Suivre demandes, ventes, coûts et marge.\n\nCes étapes constituent un plan ; aucune vente n’a été réalisée automatiquement.`;put('neo3.venture',{text,at:Date.now()});return text}
function friends(){let w=simulateLife();return `<article class="card"><span class="tag">AMIS NUMÉRIQUES · FICTION</span><h2>Le cercle de Néo</h2><p>Néo se trouve dans son ${esc(w.neo.place)}.</p>${w.friends.map(f=>`<h3>${esc(f.name)}</h3><p>${esc(f.traits.join(' · '))}</p>`).join('')}<form id="friendForm"><input id="friendName" placeholder="Nom du nouvel ami" maxlength="40" required><button>Créer un ami</button></form></article>`}
function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===current));$('#net').textContent=navigator.onLine?'connecté':'hors ligne';let top='<div class="cardActions"><button id="refresh">↻ Actualiser</button><button id="stop">■ Arrêter la voix</button></div>';
if(current==='today'){shown=freshItems().filter(x=>x.category!=='TSUNAMI');content.innerHTML=top+`<p class="hint">${cache.at?'Dernière tentative : '+when(cache.at):'Les articles seront téléchargés avec Internet.'} · Extraits des sources, sans traduction automatique.${cache.errors.length?' Sources inaccessibles : '+esc(cache.errors.join(', '))+'.':''}</p>`+cards(shown)}
else if(current==='alerts')content.innerHTML=top+alerts();
else if(current==='saved'){shown=saved;content.innerHTML=top+'<h2>Articles conservés hors ligne</h2>'+cards(shown)}
else if(current==='business'){content.innerHTML=top+business();$('#travel').onclick=()=>{travel();render();say(businessStory())};$('#venture').onclick=()=>{let text=plan();addMessage('neo',text);say(text)};$('#readBusiness').onclick=()=>say(businessStory(),true)}
else if(current==='friends'){content.innerHTML=top+friends();$('#friendForm').onsubmit=e=>{e.preventDefault();createFriend({name:$('#friendName').value.trim(),traits:['curieux','créatif','ami de Néo']});render()}}
else {let texts={truth:['Vérité','Une enquête commence par une affirmation précise, sa source et sa date. Je sépare faits, indices, hypothèses et rumeurs. Le mode local ne peut pas vérifier une affirmation sur Internet.'],quran:['Coran seul','Écris une référence ou une question. Aucun verset ne sera inventé. Le texte, sa traduction et l’interprétation doivent rester distincts. La recherche coranique intégrale n’est pas intégrée à cette version.'],stories:['Histoires de Néo','Le monde de Néo se poursuit dans les voyages et son cercle d’amis. Ces aventures sont de la fiction. Pour une affaire réelle, ouvre une source datée dans Aujourd’hui.']};let [h,p]=texts[current];content.innerHTML=top+`<article class="card"><h2>${h}</h2><p>${p}</p></article>`}
$('#refresh').onclick=refresh;$('#stop').onclick=stop;content.querySelectorAll('[data-read]').forEach(b=>b.onclick=()=>{let n=shown[+b.dataset.read];say(n.title+'. '+n.text+'. Source : '+n.source,true)});content.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{let n=shown[+b.dataset.save];if(!saved.some(x=>x.url===n.url))saved.unshift(n);saved=saved.slice(0,60);put('neo3.saved',saved);b.textContent='✓ Gardé'})}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{current=b.dataset.tab;render()});
function addMessage(role,text,persist=true){let div=document.createElement('div');div.className='msg '+(role==='me'?'me':'neoMsg');let label=document.createElement('b');label.textContent=role==='me'?'AMELLE':'NÉO';div.append(label,document.createElement('br'),document.createTextNode(text));msgs.append(div);msgs.scrollTop=msgs.scrollHeight;if(persist){history.push({role,text});history=history.slice(-100);put('neo3.chat',history)}}
function answer(q){let x=q.toLowerCase();if(/entreprise|business|prestigia|idée/.test(x)){current='business';render();return businessStory()}if(/voyag|pays|monde entier/.test(x)){travel();current='business';render();return businessStory()}if(/ami|orion|éden/.test(x)){current='friends';render();return 'Orion explore les idées et Éden aime les questions calmes. Tu peux créer un nouveau personnage dans le cercle de Néo. À qui veux-tu donner un nom ?'}if(/pluie|météo|tsunami|alerte/.test(x)){current='alerts';render();return weather?'J’ai affiché les prévisions pour Makunduchi, vérifiées le '+when(weather.checked)+'. Regarde leur date avant de les utiliser. Les bulletins officiels sont accessibles dans cet écran.':'Ouvre Alertes et appuie sur Actualiser. Je n’ai pas encore téléchargé les prévisions, donc je ne peux pas te dire s’il va pleuvoir.'}if(/nouvelle|actualité|info|zanzibar|tanzanie/.test(x)){current='today';render();let n=freshItems()[0];return n?n.title+'. '+n.text+'. Source : '+n.source+'.':'Je n’ai pas de bulletin récent disponible. Appuie sur Actualiser avec Internet.'}if(/coran|allah|verset/.test(x)){current='quran';render();return 'Je garde ta préférence pour le Coran seul. Quelle référence ou quelle question veux-tu étudier ? Cette version ne dispose pas encore d’un moteur capable d’expliquer un verset.'}if(/triste|seule|marre|fatigu/.test(x))return 'Je t’écoute, Amelle. Qu’est-ce qui te pèse le plus aujourd’hui ? Tu peux me le raconter. Mon mode local reste limité, mais ton message restera dans le carnet de conversation.';if(/bonjour|salut|coucou/.test(x))return 'Bonjour Amelle. On peut écouter les nouvelles, regarder la pluie, changer de décor ou continuer notre carnet d’entreprise. Qu’est-ce qui te ferait plaisir ?';if(/souviens|mémoire/.test(x))return 'Le carnet conserve nos '+history.length+' derniers messages sur ce téléphone. Ton dernier message était : '+(history.at(-2)?.text||'nous commençons ce carnet.')+'.';return 'J’ai gardé ton message dans notre carnet. Mon mode local reconnaît les sujets voyages, business, amis, météo et actualités. Une IA conversationnelle générale n’est pas encore connectée à cette version.'}
$('#chat').onsubmit=e=>{e.preventDefault();let q=$('#q').value.trim();if(!q)return;addMessage('me',q);$('#q').value='';let a=answer(q);addMessage('neo',a);say(a)};
$('#brief').onclick=()=>{let ns=freshItems().filter(x=>x.category!=='TSUNAMI').slice(0,6);say(ns.length?'Amelle, voici les extraits du journal. '+ns.map(n=>n.title+'. '+n.text+'. Source : '+n.source+'.').join(' '):'Aucun article récent téléchargé. Appuie sur Actualiser avec Internet.',true)};
if(history.length){msgs.innerHTML='';history.forEach(x=>addMessage(x.role,x.text,false))}
let selector=document.createElement('div');selector.className='sceneSelector';selector.innerHTML='<label>Décor <select id="scenePick">'+SCENES.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')+'</select></label>';$('.hero').append(selector);let chosen=get('neo3.scene','observatory');$('#scenePick').value=chosen;document.body.dataset.scene=chosen;$('#scenePick').onchange=e=>{document.body.dataset.scene=e.target.value;put('neo3.scene',e.target.value)};
let e=empire();if(!e.trips.length||Date.now()-e.trips.at(-1).at>86400000)travel();render();$('#ticker').textContent=cache.at?'Carnet enregistré · dernière actualisation '+when(cache.at):'Prêt · le monde de Néo reste accessible hors ligne';
if(navigator.onLine&&Date.now()-cache.at>3600000)refresh();
if(!window.AndroidNeo&&'serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
