const $=s=>document.querySelector(s),content=$("#content"),neo=$("#neo"),msgs=$("#messages");
const NEWS=[
{cat:"ZANZIBAR",ttl:48,title:"Stone Town : un hôtel historique change de mains",text:"Infinity Developments a acquis Beit Al Salaam et prévoit sa rénovation.",source:"The Citizen",url:"https://www.thecitizen.co.tz/tanzania/zanzibar/zanzibar-developer-acquires-new-hotel-in-stone-town-5620462",at:"2026-10-05T08:00:00+03:00"},
{cat:"MÉTÉO",ttl:72,title:"Pluies : la Tanzanie prend des précautions",text:"La fermeture des écoles continentales a été avancée face au risque de fortes pluies annoncé pour octobre-décembre.",source:"The Citizen / TMA",url:"https://www.thecitizen.co.tz/tanzania/news/national/tanzania-brings-forward-school-closing-date-over-el-ni%C3%B1o-rain-concerns-5617914",at:"2026-10-03T08:00:00+03:00"},
{cat:"HUMANOÏDES",ttl:48,title:"La robotique industrielle accélère encore",text:"RobCo annonce une valorisation d'un milliard de dollars et prépare Alfie, un robot à deux bras auto-apprenant.",source:"Reuters",url:"https://www.reuters.com/legal/transactional/german-robot-startup-robco-hits-1-billion-valuation-ceo-moves-us-2026-10-05/",at:"2026-10-05T08:00:00+03:00"}];
const tabs={truth:["MODE VÉRITÉ","Je ne choisis jamais une version parce qu'elle est officielle ou alternative. Je remonte à l'origine, cherche les preuves et tente de réfuter ma propre conclusion.","FAIT 🟢 · INDICE 🟡 · HYPOTHÈSE 🟠 · RUMEUR 🔴 · INCONNU ⚪"],quran:["MODE CORAN","Le Coran est ma référence religieuse. Je distingue toujours le texte arabe, la traduction et mon interprétation. Je n'invente jamais un verset.","📖 Texte · Traduction · Réflexion"],stories:["LE SOMBRE & HISTOIRES","Affaires vraies, héritages, justice, espionnage, opérations déclassifiées et mystères. Je raconte sans transformer le spectaculaire en preuve.","🕯️ DOCUMENTÉ · CONTESTÉ · INCONNU"]};
function fresh(n){return Date.now()-new Date(n.at).getTime()<n.ttl*36e5}
function today(){let ns=NEWS.filter(fresh);content.innerHTML='<div class="pulse"><b>● DIRECT</b> '+ns.length+' sujets encore frais</div>'+ns.map(n=>'<article class="card"><span class="tag">'+n.cat+'</span><h2>'+n.title+'</h2><p>'+n.text+'</p><footer>'+n.source+' · expire automatiquement</footer><a target="_blank" rel="noopener" href="'+n.url+'">Voir la source ↗</a></article>').join("")}
function tab(k){if(k==="today")return today();let [h,p,t]=tabs[k];content.innerHTML='<article class="card feature"><span class="tag">'+t+'</span><h2>'+h+'</h2><p>'+p+'</p></article>'}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>tab(b.dataset.tab));today();
function say(t){if(!("speechSynthesis"in window))return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang="fr-FR";u.rate=.94;u.pitch=.88;u.onstart=()=>neo.classList.add("talking");u.onend=()=>neo.classList.remove("talking");speechSynthesis.speak(u)}
$("#speak").onclick=()=>say("Bonjour Amelle. Je suis Néo. Je ne te promets pas de tout savoir. Je te promets de distinguer ce que je sais de ce que j'ignore, et de chercher les preuves avant de conclure.");
function answer(q){let x=q.toLowerCase();if(/coran|allah|verset/.test(x))return"Sur le Coran, je ne mélange jamais le texte avec mon opinion. Donne-moi une sourate, un verset ou une question et je séparerai citation, traduction et réflexion.";if(/vérité|vrai|mensonge|preuve|complot/.test(x))return"Mode Vérité activé. Je veux l'affirmation exacte. Ensuite je cherche son origine, les preuves qui la soutiennent et celles qui la contredisent. Si les preuves ne suffisent pas, ma réponse sera : inconnu.";if(/nouvelle|info|zanzibar|tanzanie/.test(x))return"J'ai "+NEWS.filter(fresh).length+" sujets frais dans mon journal local. Ouvre Aujourd'hui. La prochaine étape reliera ce tableau directement aux flux Internet.";return"Je t'écoute. Pour l'instant mon cerveau embarqué sait gérer mes modes locaux. La couche suivante ajoutera le moteur de recherche et le modèle conversationnel."}
$("#chat").onsubmit=e=>{e.preventDefault();let q=$("#q").value.trim();if(!q)return;msgs.insertAdjacentHTML("beforeend",'<div class="msg me">'+q.replace(/[<>]/g,"")+'</div>');let a=answer(q);msgs.insertAdjacentHTML("beforeend",'<div class="msg"><b>NÉO</b><br>'+a+'</div>');$("#q").value="";say(a)}
$("#listen").onclick=()=>{let R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){say("La reconnaissance vocale du navigateur n'est pas disponible ici. Tu peux m'écrire.");return}let r=new R();r.lang="fr-FR";r.interimResults=false;r.onstart=()=>$("#status").textContent="Je t'écoute…";r.onresult=e=>{$("#q").value=e.results[0][0].transcript;$("#chat").requestSubmit()};r.onend=()=>$("#status").textContent="Je cherche les faits. Je distingue le certain de l'inconnu.";r.start()};
let deferred;addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferred=e});$("#install").onclick=()=>deferred&&deferred.prompt();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");